apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  namespace: default
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: silverdeath366/monitor:latest
          command: ["python3"]
          args: ["monitor.py"]
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-credentials
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-credentials
                  key: TELEGRAM_CHAT_ID
